# Generated by Django 6.1.2 on 2026-10-08 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=80)),
                ('details', models.TextField(default='{}')),
                ('prev_hash', models.CharField(max_length=64)),
                ('entry_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('dob', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=8)),
                ('allergies', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('lab', 'Lab Technician'), ('pharmacist', 'Pharmacist')], default='doctor', max_length=20)),
                ('department', models.CharField(default='General', max_length=80)),
                ('enc_public_pem', models.TextField()),
                ('enc_private_pem', models.TextField()),
                ('sig_public_pem', models.TextField()),
                ('sig_private_pem', models.TextField()),
                ('key_fingerprint', models.CharField(max_length=64)),
                ('ca_certificate', models.TextField(blank=True)),
                ('revoked', models.BooleanField(default=False)),
                ('key_version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('ciphertext_b64', models.TextField()),
                ('wrapped_dek_b64', models.TextField()),
                ('iv_b64', models.CharField(max_length=64)),
                ('digest_hex', models.CharField(max_length=64)),
                ('signature_b64', models.TextField()),
                ('nonce_hex', models.CharField(max_length=64)),
                ('msg_id', models.CharField(max_length=64, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SEALED', 'Sealed'), ('DELIVERED', 'Delivered'), ('OPENED', 'Opened & verified'), ('TAMPER_ALERT', 'Tamper detected')], default='SEALED', max_length=20)),
                ('sender_key_version', models.IntegerField(default=1)),
                ('recipient_key_version', models.IntegerField(default=1)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='secure_exchange.patient')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_reports', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='UsedNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce_hex', models.CharField(max_length=64)),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipient', 'nonce_hex'), name='unique_nonce_per_recipient')],
            },
        ),
    ]
