# Generated by Django 6.1.2 on 2026-10-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_enc_keys',
            field=models.TextField(default='[]'),
        ),
    ]
